name: vlam
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.4
  - libexpat=2.7.4
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.19
  - packaging=25.0
  - pip=26.0.1
  - python=3.11.14
  - setuptools=80.10.2
  - sqlite=3.51.1
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.46.3
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - accelerate==1.12.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.1
      - attrs==25.4.0
      - bitsandbytes==0.49.1
      - brotli==1.2.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - clip==1.0
      - colorama==0.4.6
      - contourpy==1.3.3
      - cut-cross-entropy==25.1.1
      - cycler==0.12.1
      - datasets==3.4.1
      - diffusers==0.36.0
      - dill==0.3.8
      - distro==1.9.0
      - docstring-parser==0.17.0
      - fastapi==0.129.0
      - ffmpy==1.0.0
      - filelock==3.20.0
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2024.9.0
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.46
      - gradio==6.5.1
      - gradio-client==2.0.3
      - groovy==0.1.2
      - h11==0.16.0
      - hf-transfer==0.1.9
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.2
      - idna==3.11
      - importlib-metadata==8.7.1
      - jinja2==3.1.6
      - jiter==0.13.0
      - kiwisolver==1.4.9
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgspec==0.20.0
      - multidict==6.7.1
      - multiprocess==0.70.16
      - networkx==3.6.1
      - numpy==2.3.5
      - openai==2.20.0
      - opencv-python==4.13.0.92
      - orjson==3.11.7
      - pandas==3.0.0
      - peft==0.18.1
      - pillow==12.0.0
      - platformdirs==4.7.1
      - polars==1.38.1
      - polars-runtime-32==1.38.1
      - propcache==0.4.1
      - protobuf==6.33.5
      - psutil==7.2.2
      - pyarrow==23.0.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - pygments==2.19.2
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.22
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2026.1.15
      - requests==2.32.5
      - rich==14.3.2
      - safehttpx==0.1.7
      - safetensors==0.7.0
      - scipy==1.17.0
      - semantic-version==2.10.0
      - sentencepiece==0.2.1
      - sentry-sdk==2.52.0
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - starlette==0.52.1
      - sympy==1.14.0
      - tokenizers==0.22.2
      - tomlkit==0.13.3
      - torch==2.10.0+cu126
      - torchao==0.16.0
      - torchvision==0.25.0+cu126
      - tqdm==4.67.3
      - transformers==4.57.6
      - triton-windows==3.6.0.post25
      - trl==0.24.0
      - typeguard==4.4.4
      - typer==0.23.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tyro==1.0.6
      - tzdata==2025.3
      - ultralytics==8.4.14
      - ultralytics-thop==2.0.18
      - unsloth==2026.2.1
      - unsloth-zoo==2026.2.1
      - urllib3==2.6.3
      - uvicorn==0.40.0
      - wandb==0.25.0
      - wcwidth==0.6.0
      - xformers==0.0.34
      - xxhash==3.6.0
      - yarl==1.22.0
      - yt-dlp==2026.2.4
      - zipp==3.23.0
prefix: C:\conda\envs\vlam
